name: real

device:
  type: cuda
  ids: [0,3]
precision:
  amp: true


dataloader:
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  non_blocking: true

profiling:
  enabled: true
  record_timing: true
  record_memory: true
